'''
Runs the network with the parameters load from a file generated by 'find_oscillations.py'
'''

import pickle
import os
from pathlib import Path
from src.RNN import RNN
from matplotlib import pyplot as plt
N = 5
lmbd = 0.5
dt = 0.1
file_name = f"params_{N}_{lmbd}.pkl"
file_path = os.path.join(Path(os.getcwd()).parent, "data", file_name)
param_dict = pickle.load(open(file_path, "rb+"))

rnn = RNN(dt, lmbd, param_dict["W"], param_dict["b"])
T = 50
rnn.run(T)
fig, ax = rnn.plot_history()
plt.show(block=True)